pretrained_root: null
checkpoint_root: null
wandb_name: llada_3B
seed: 114514
ref_duration: 184.32
clamp3_path: clamp3/weights_clamp3_saas_h_size_768_t_model_FacebookAI_xlm-roberta-base_t_length_128_a_size_768_a_layers_12_a_length_128_s_size_768_s_layers_12_p_size_64_p_length_512.pth
clamp_dropout: 0.5
clamp_cond: prefix
data:
  name: audio_text_data_v2
  have_subdir: true
  train_fp: /path/to/metadata/train.txt
  val_fp: /path/to/metadata/val.txt
  meta_fp: /path/to/metadata/metas.pkl
  duration: 163.84
  sr: 48000
  channels: 2
  voc_dir: /path/to/vocals
  voc_suffix: m4a
  acc_dir: /path/to/accompaniments
  acc_suffix: m4a
  noise:
    name: off
    sigma: 0.0
  frequency_balance:
    enabled: true
    prob: 0.7
    apply_to_voc: false
    apply_to_acc: true
    apply_to_ref: true
    bass:
      min_cut_db: 2.0
      max_cut_db: 5.0
      freq_min: 80.0
      freq_max: 180.0
      q_min: 0.6
      q_max: 1.1
    mid:
      min_gain_db: 1.0
      max_gain_db: 3.0
      freq_min: 1200.0
      freq_max: 2600.0
      q_min: 0.6
      q_max: 1.2
    treble:
      min_gain_db: 1.0
      max_gain_db: 3.5
      freq_min: 3200.0
      freq_max: 5800.0
      q_min: 0.6
      q_max: 1.0
  batch_size: 1
  num_workers: 8
  voc:
    size: 16384
  acc:
    size: 16384
  special_tokens:
    voc_pad: 16384
    acc_mask: 16384
    acc_pad: 16385
model:
  llama:
    json_path: null
    pretrained:
      enabled: false
      path: null
      ignore_mismatched_sizes: true
      local_files_only: true
    is_decoder: false
    head_dim: 128
    hidden_act: silu
    initializer_range: 0.02
    intermediate_size: 8192
    hidden_size: 3072
    num_hidden_layers: 28
    num_attention_heads: 24
    num_key_value_heads: 8
    vocab_size: 1
    attention_dropout: 0.1
  name: llama
moa:
  enabled: false
optim:
  name: adamw
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.01
  lr: 1e-5
  scheduler:
    name: cos
    warmup: 5000
    num_training_steps: 300000
train:
  max_steps: 10000
  check_val_every_n_steps: 1500
  gradient_checkpointing: true
  acc_grad: 8
  grad_clip: 1.0
  precision: bf16-mixed
  force_fp32: false
wandb: true
loss:
  name: ce
  label_smoothing: 0.0
  rtd:
    enabled: true
    weight: 0.2
    sampling: argmax
    temperature: 1.0
config_root: lada_band/conf
data_config: data/toy_data.yaml
codec_path: mucodec/mucodec.pt
project: llada
l_ckpt_fp: 3B_test.ckpt
ckpt_dir: null
resume_ckpt_fp: null
resume_training: false
